Merge commits from dev branch
alphelvaci/hipo-exercise pull request #30
Opened 2021-01-01 09:43 UTC by alphelvaci

2021-01-01 10:13 UTC, yigitguler requested changes
Minor issues. Looks great. The only real issue is that this PR is too big :) You could divide this PR to multiple steps. 

 - Crispy forms
 - View class changes
 - Other minor changes

2021-01-01 10:13 UTC, yigitguler commented on recipes/models.py
> +    slug = AutoSlugField(populate_from='name', overwrite=True)
`overwrite=True` burada neyi sağlıyor?

2021-01-01 10:13 UTC, yigitguler commented on recipes/models.py
> +    EASY = 'easy'
We have a naming convention here:

DIFFICULTY_CHOICE_EASY

2021-01-01 10:13 UTC, yigitguler commented on recipes/templates/recipes/sidebar.html
> +        {% for field in search_form %}
What about errors?

2021-01-01 10:13 UTC, yigitguler commented on recipes/urls.py
> +    path('edit_recipe/<int:pk>', views.edit_recipe.as_view(), name='edit_recipe'),
Always use tailing slashes . It is a Django convention.

Also, we should use hypens instead of underscores in the URLS.

create-recipe/
edit-recipe/<int:pk>/

ALSO

/ -->list
/recipes/create/ -->create
/recipes/<int:pk>/ --> Detail view
/recipes/<int:pk>/edit/ --> Edit view

This is even better

2021-01-01 10:13 UTC, yigitguler commented on recipes/views.py
> +class index(ArchiveIndexView):
This is OK, but I suggest you to use ListView here.

2021-01-01 10:13 UTC, yigitguler commented on recipes/views.py
> +class recipe_detail(DetailView):
Classes should be CapitalCase
https://www.python.org/dev/peps/pep-0008/#class-names

2021-01-01 10:20 UTC, alphelvaci commented on recipes/models.py
> +    slug = AutoSlugField(populate_from='name', overwrite=True)
Obje her kaydediğildiğinde slug'ı yeniden oluşturuyor

2021-01-01 10:21 UTC, alphelvaci commented on recipes/models.py
> +    EASY = 'easy'
will fix.

2021-01-01 10:23 UTC, alphelvaci commented on recipes/templates/recipes/sidebar.html
> +        {% for field in search_form %}
Django automatically did not let me submit the form if it was invalid. Is there a specific error I should be aware of?

2021-01-01 10:23 UTC, alphelvaci commented on recipes/urls.py
> +    path('edit_recipe/<int:pk>', views.edit_recipe.as_view(), name='edit_recipe'),
will fix.

2021-01-01 10:23 UTC, alphelvaci commented on recipes/views.py
> +class recipe_detail(DetailView):
will fix.

2021-01-01 10:23 UTC, alphelvaci commented on recipes/views.py
> +class index(ArchiveIndexView):
will fix.

2021-01-01 10:29 UTC, yigitguler commented on recipes/templates/recipes/sidebar.html
> +        {% for field in search_form %}
We should always display field errors and non_field_errors. It is a good convention.

2021-01-10 07:08 UTC, yigitguler commented on recipes/views.py
> +        return redirect('/recipe/' + str(recipe.id))
Use reverse URL function to obtain the path.
https://docs.djangoproject.com/en/3.1/ref/urlresolvers/

2021-01-10 07:09 UTC, yigitguler approved these changes
Just one minor issue.

2021-01-10 08:47 UTC, merged